/**
 * Copyright (c) 2013 Oracle and/or its affiliates. All rights reserved.
 *
 * You may not modify, use, reproduce, or distribute this software except in
 * compliance with  the terms of the License at:
 * http://java.net/projects/javaeetutorial/pages/BerkeleyLicense
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nzo;

import java.util.HashSet;
import java.util.Set;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

/**
 *
 * @author ievans
 */
@ApplicationPath("/")
public class RestApplication extends Application {
    @Override
    public Set<Class<?>> getClasses() {
        final Set<Class<?>> classes = new HashSet<>();
        // register root resource
        classes.add(RestCv.class);
        classes.add(RestEducation.class);
        classes.add(RestEntreprise.class);
        classes.add(RestExperience.class);
        classes.add(RestJobs.class);
        classes.add(RestLanguage.class);
        classes.add(RestPostule.class);
        classes.add(RestResume.class);
        classes.add(RestUsers.class);
        classes.add(RestVideo.class);
        
        
        
        return classes;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(nzo.RestCv.class);
        resources.add(nzo.RestEducation.class);
        resources.add(nzo.RestEntreprise.class);
        resources.add(nzo.RestExperience.class);
        resources.add(nzo.RestJobs.class);
        resources.add(nzo.RestLanguage.class);
        resources.add(nzo.RestPostule.class);
        resources.add(nzo.RestResume.class);
        resources.add(nzo.RestUsers.class);
        resources.add(nzo.RestVideo.class);
    }

}
